version: '3'

services:
  db:
    image: postgres:alpine3.19
    environment:
      POSTGRES_DB: "eksdb"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - 5003:5432
  api:
    depends_on:
      - 'db'
    build: ./api
    volumes:
      - ./api:/usr/src/app
    ports:
      - 5001:80
  client:
    build: ./client
    volumes:
      - ./client:/usr/src/app
    ports:
      - 5002:80
  