version: '3'

services:
  api:
    build: ./api
    volumes:
      - ./api:/usr/src/app
    ports:
      - 5001:80
  client:
    build: ./client
    volumes:
      - ./client:/usr/src/app
    ports:
      - 5002:80
  